export const ProfileList=[
    {
        id:1,
        content:'Our Partnerships With Multinational Companies Are Long-Term And Based On Earned Trust. APM Has Established Relationships With Its Customers For 5, 10 And Even 25 Continuous Years.'
    },
    {
        id:2,
        content:'In The 1990\'S, Our Founder Mr. Dayanand Agarwal Innovated Single Source Responsibility, An Accountability Principle That Continues To Differentiate Agarwal Packers & Movers Today.'
    },
    {
        id:3,
        content:'The Same Skilled Professional Driver Is Responsible For Packing, Loading, Hauling, Unloading And Unpacking At Origin And Destination With The Same And Familiar Qualified Crew At Both Ends.'
    },
    {
        id:4,
        content:'Single Source Responsibility Promotes High-Quality Relocation Services And Holds Everyone Accountable From Point A To Point B, Year In And Year Out Without Regard To Seasonal Variation.'
    },
    {
        id:5,
        content:'Nationwide Network. Our Regional Infrastructure Network Provides Quality Capacity For Short Haul, Long Distance, Intrastate, Local And Canada Cross Border Moving And Storage.'
    },
    {
        id:6,
        content:'We Align Our Capacity, Businesses Processes, And Continuous Improvement Culture Around Our Client Businesses, Strategies, And Goals.'
    },
    {
        id:7,
        content:'Our Financial Strength. With The Uncertainty Of Global Financial Markets, Energy Costs, Credit Tightening, Corporate And Supply Chain Profitability; Agarwal Packers & Movers Remains On Very Strong Financial Footing. We Continue To Invest In Our Core Business, Adding To The Security Of Our Partnerships Long Term.'
    },
    {
        id:8,
        content:''
    },
    {
        id:9,
        content:''
    },
    {
        id:10,
        content:''
    },
    {
        id:11,
        content:''
    },
    {
        id:12,
        content:''
    },
    {
        id:13,
        content:''
    },
    {
        id:14,
        content:''
    },
    {
        id:15,
        content:''
    },
    {
        id:1,
        content:''
    },
    {
        id:1,
        content:''
    },
    {
        id:1,
        content:''
    },
    {
        id:1,
        content:''
    },
    {
        id:1,
        content:''
    },
    {
        id:1,
        content:''
    },
    {
        id:1,
        content:''
    },
]